import turtle
import time

screen = turtle.Screen()
tp=turtle.Turtle()
screen.setup(620,320)
screen.bgcolor("black")

#Lapsi
tp.pensize(3)
tp.speed(5)
tp.color('white')

#vendos lapsin per germen i
tp.penup()
tp.setpos(-280,140)
tp.pendown()

#fillon e vizaton germen I
tp.fillcolor('green')
tp.begin_fill()
tp.rt(90)
tp.forward(200)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(200)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(200)
tp.end_fill()

#vendos lapsin per germen S
tp.penup()
tp.setpos(-150,140)
tp.pendown()

#vizato germen s
tp.fillcolor('red')
tp.begin_fill()
tp.right(90)
tp.forward(90)
tp.left(90)
tp.forward(100)
tp.left(90)
tp.forward(90)
tp.right(90)
tp.forward(90)
tp.right(90)
tp.forward(90)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(100)
tp.left(90)
tp.forward(110)
tp.left(90)
tp.forward(90)
tp.right(90)
tp.forward(80)
tp.right(90)
tp.forward(90)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(90)
tp.end_fill()

#vendos lapsin per germen E
tp.penup()
tp.setpos(-20,140)
tp.pendown()

#vizaton germen e
tp.fillcolor('yellow')
tp.begin_fill()
tp.forward(90)
tp.left(90)
tp.forward(200)
tp.left(90)
tp.forward(90)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(80)
tp.right(90)
tp.forward(85)
tp.right(90)
tp.forward(80)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(80)
tp.right(90)
tp.forward(85)
tp.right(90)
tp.forward(80)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(90)
tp.end_fill()

#vendos lapsin per germen L
tp.penup()
tp.setpos(10,140)
tp.pendown()

#vizaton germen L
tp.fillcolor('purple')
tp.begin_fill()
tp.left(90)
tp.forward(200)
tp.left(90)
tp.forward(90)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(80)
tp.right(90)
tp.forward(190)
tp.left(90)
tp.forward(10)
tp.left(90)
tp.forward(200)
tp.end_fill()

#vendos lapsin per germen D
tp.penup()
tp.setpos(120,140)
tp.pendown()

#vizato geremn D
tp.fillcolor('blue')
tp.begin_fill()
tp.forward(200)
tp.left(90)
tp.forward(10)
tp.circle(100, 180)
tp.forward(10)
tp.end_fill()

tp.penup()
tp.setpos(130,120)
tp.pendown()

#vizato grpoen mrena D
tp.fillcolor('black')
tp.begin_fill()
tp.left(90)
tp.forward(160)
tp.left(90)
tp.forward(10)
tp.circle(75,90)
tp.forward(10)
tp.circle(75,90)
tp.forward(10)
tp.left(90)
tp.forward(100)
tp.end_fill()
tp.ht()


turtle.done()